### ISSUE TITLE
Incompatablity with Greg's SGCraft's CC SG Interface

### ISSUE THREAD

**Issue by NicolaosGreene** [OpenMods/OpenPeripheral#221] opened 2015-01-10 09:45 UTC
When I have OpenPeripherals installed I get the following crash whenever I attempt connect a modem to the CC SG Interface http://openeye.openmods.info/crashes/d4bd6c3dfff959ad7a0318a5c6df78d7

**Comment by boq** [comment] 2015-01-10 10:41
Ok, I see two problems here: 
- Duplicate of #206, #207, #217, OpenMods/OpenPeripheral-Addons#40, OpenMods/OpenPeripheral-Addons#42, OpenMods/OpenPeripheral-Integration#1 and few others - some mod (ProjectRed again?) bundles old API and it breaks Computercraft itself
- We removed SGCraft itegration in 1.7, because they have added their own. But since they do few not-so-smart things (registering peripheral in `postInit` and making ALL tile entities `IInventory`) OpenPeripheral tries to supply own methods, overriding original implementation. I have limited ability to control that, but I tried to do what I can in [this](http://www.openmods.info:8080/job/OpenPeripheralCore/180/) snapshot. You can also try to complain to SGCraft author(s) about that partially broken design.

**Closed by boq** 2015-01-10 10:41 UTC

**Comment by NicolaosGreene** [comment] 2015-01-10 18:22
The new snapshot fixes any problems that there were, thanks for your time and thorough answer.

**Comment by alexgurrola** [comment] 2015-01-15 11:04
I had the same issue and it was fixed with this snapshot.  It even connects on the sides of the computer now.  Thanks so very, very much.
