### ISSUE TITLE
Noteblock connecting to modem crashes server[1.7.10]

### ISSUE THREAD

**Issue by Doyle3694** [OpenMods/OpenPeripheral#223] opened 2015-01-11 12:43 UTC
Wired modems connecting directly to noteblocks crashes the server(see attached bug report) fortunately it does not corrput your world and the modem stays connected. It does work with peripheral proxies, however. I do not know if this is a problem on your side or computercraft's side but I can pass it on to the guys at computercraft if you want to as well.

Crash log: http://pastebin.com/hxFMZsVZ

**Comment by boq** [comment] 2015-01-11 12:56
Duplicate of #206, #207, #217, #223, OpenMods/OpenPeripheral-Addons#40, OpenMods/OpenPeripheral-Addons#42, OpenMods/OpenPeripheral-Integration#1.

**Closed by boq** 2015-01-11 12:56 UTC
